apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: prod-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      serviceAccountName: hello-world-sa
      containers:
        - name: hello-world-app
          image: northamerica-northeast1-docker.pkg.dev/axiomatic-set-447623-d6/hello-world-repo/hello-world-image:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
