apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: qa-namespace # Or your desired namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: northamerica-northeast1-docker.pkg.dev/axiomatic-set-447623-d6/hello-world-repo/hello-world-image:46
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: qa-namespace # Must be the same namespace as the Deployment
spec:
  selector:
    app: hello-world-app # Matches the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80 # The port the service exposes
      targetPort: 8080 # The port the container listens on
  type: LoadBalancer # Or NodePort if you don't have a LoadBalancer setup